### ISSUE TITLE
Verifying SBOM reference with cosign verify-attestation returns error

### ISSUE THREAD

**Issue by garrying** [chainguard-dev/edu#1105] opened 2023-11-01 22:11 UTC
**Describe the bug**
The command to verify SBOMs using `cosign verify-attestation` returns an saying that `--platform` is an unknown flag.

**To Reproduce**
1. Go to https://edu.chainguard.dev/chainguard/chainguard-images/reference/go/provenance_info/#downloading-and-verifying-sboms (applicable to all images with `provenance_info` I think)
2. Copy
  ```
cosign verify-attestation \
  --type https://spdx.dev/Document \
  --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
  --certificate-identity=https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main \
  --platform=linux/amd64 \
  cgr.dev/chainguard/go
  ```
4. Run command
5. Error:
  ```
Error: unknown flag: --platform
main.go:74: error during command execution: unknown flag: --platform
  ```

**Expected behavior**
Should display verification without error.

**Additional context**
Reproduced using cosign 2.2.0

**Comment by ltagliaferri** [comment] 2023-11-02 18:36
This is a dupe of this issue, I'll close + link to this to track there: https://github.com/chainguard-dev/internal/issues/3362

**Closed by ltagliaferri** 2023-11-02 18:36 UTC
